name: Windows EXE Build

on:
  workflow_dispatch:
  push:
    paths:
      - '纳米孔/cpp_port/**'
      - '.github/workflows/windows-exe.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Qt (install-qt-action)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.3'
          modules: 'qtcharts'

      - name: Configure (MSVC 2022 x64)
        shell: pwsh
        run: |
          $cmakePrefix = "$Env:QTDIR\lib\cmake"
          cmake -S "纳米孔/cpp_port" -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="$cmakePrefix"

      - name: Build (Release)
        shell: pwsh
        run: cmake --build build --config Release -j

      - name: Deploy with windeployqt
        shell: pwsh
        run: |
          $qtbin = "$Env:QTDIR\bin"
          & "$qtbin\windeployqt.exe" --release build\Release\nanopore_cpp.exe

      - name: Package artifact
        shell: pwsh
        run: |
          Compress-Archive -Path build\Release\* -DestinationPath nanopore_cpp_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nanopore_cpp_windows
          path: nanopore_cpp_windows.zip